# Generated by Django 4.2.4 on 2023-08-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fullname', models.CharField(blank=True, max_length=180, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalFieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('is_displayed', models.BooleanField(default=False)),
            ],
        ),
    ]
